# Generated by Django 4.2.7 on 2024-01-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='partsstructurechangeset',
            table='bom_parts_structure_change_set',
        ),
        migrations.AlterModelTable(
            name='partsstructurehistory',
            table='bom_parts_structure_history',
        ),
        migrations.AlterModelTable(
            name='undoredopointer',
            table='bom_undo_redo_pointer',
        ),
    ]
